<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_A10" Id="{61bf9701-30d1-49ea-a466-b92010020989}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_A10
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_A10">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>