<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_A20" Id="{c114c468-3561-4b70-8115-825212b13cd3}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_A20
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="M_Test" Id="{1f305778-8145-43f9-93e1-f6337ff24382}">
      <Declaration><![CDATA[METHOD M_Test : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[//////////////add test here///////////////////////////]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_A20">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_A20.M_Test">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>