<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_A10" Id="{61bf9701-30d1-49ea-a466-b92010020989}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_A10
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="M_Abort" Id="{ec7271ad-62d8-42d8-b9e0-1e94d17bc68a}">
      <Declaration><![CDATA[METHOD M_Abort : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="M_Execute" Id="{024bf813-14fe-48ca-a872-798b2f543621}">
      <Declaration><![CDATA[METHOD M_Execute : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="M_reset" Id="{29fb3e66-dea3-478b-9f0c-92be7a310a7e}">
      <Declaration><![CDATA[METHOD M_reset : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[//////////////////////reset all error here////////////////////////////]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_A10">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_A10.M_Abort">
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="FB_A10.M_Execute">
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="FB_A10.M_reset">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>