<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_Generic" Id="{2d1028d7-c68c-409c-9f71-89e7fa3d0153}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Generic
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="M_reset" Id="{ad4fd229-39b4-463c-aa80-3ba7b32291d6}">
      <Declaration><![CDATA[METHOD M_reset : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_Generic">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_Generic.M_reset">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>