<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{9b544d30-5de0-4bac-a48a-e1f991a5356f}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	a10	: BOOL;
	a20	: BOOL;
	fb_a10	:FB_A10;
	fb_a20	: FB_A20;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>